### ISSUE TITLE
Translate and __init__.py problem

### ISSUE THREAD

**Issue by N3CH0** [ardha27/AI-Waifu-Vtuber#12]
Hello this is me again, Im sry but there's a problem with the translator, **the translator didn't translate** for example:
"Hello" it translate to "you" or "How are you?" it translate to "Thank you"
This happen after I restart my computer, before I restart my computer the translator seems normal.

**__init__.py problem:**
This is also apeared after I restart my computer, Error log:

Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: 
Traceback (most recent call last):
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 211, in <module>       
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 67, in record_audio
    transcribe_audio("input.wav")
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 83, in transcribe_audio
    result = translate_google(chat_now, "ID", "EN")
  File "C:\oof\AI\AI-Waifu-Vtuber-master\translate.py", line 39, in translate_google
    result = translator.translate(text, src=source, dest=target)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 219, in translate
    parsed = json.loads(data[0][2])
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray not NoneType'
TypeError: the JSON object must be str, bytes or bytearray not NoneTypenot NoneType

I tried to reexecute .\run.py, the error showed up again, but this time "not NoneTyp" was duplicated :
First error log :
TypeError: the JSON object must be str, bytes or bytearray not NoneTypenot NoneType
Second error log :
TypeError: the JSON object must be str, bytes or bytearray not NoneTypenot NoneTypenot NoneType

And repeated, any Idea what happen?

**Comment by ardha27** [comment]
I think it's because you didn't say anything on the mic, so the translate function passing nothing and makes the translate program getting error
