### ISSUE TITLE
why i still got this even though i dont have that line 

### ISSUE THREAD

**Issue by KiyoshiTheBoss** [ardha27/AI-Waifu-Vtuber#19]
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master> python .\run.py
Traceback (most recent call last):
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\run.py", line 14, in <module>     
    from utils.TTS import *
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\utils\TTS.py", line 5, in <module>
    from utils.katakana import *
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\utils\katakana.py", line 1, in <module> 
    import MeCab
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: The specified module could not be found.
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master>

**Comment by KiyoshiTheBoss** [comment]
in run.py the katakana_text = katakana_converter(tts) is not there and i still got this problem like how

**Comment by ardha27** [comment]
delete this two line in run.py

from utils.TTS import *
katakana_text = katakana_converter(tts)

**Comment by KiyoshiTheBoss** [comment]
now this sigh

PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)> & "C:/Program Files/Python311/python.exe" "c:/Users/60107/Downloads/AI-Waifu-Vtuber-master (1)/AI-Waifu-Vtuber-master/run.py"
Traceback (most recent call last):
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 16, in <module>
    from utils.TTS import *
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\TTS.py", line 5, in <module> 
    from utils.katakana import *
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\katakana.py", line 1, in <module>
    import MeCab
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\MeCab\__init__.py", line 10
    from . import _MeCab==0.996.3
IndentationError: unexpected indent

**Comment by KiyoshiTheBoss** [comment]
oh oh it work now thank you
