### ISSUE TITLE
hmmm what is and how to fix it ?

### ISSUE THREAD

**Issue by KiyoshiTheBoss** [ardha27/AI-Waifu-Vtuber#20]
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)> & "C:/Program Files/Python311/python.exe" "c:/Users/60107/Downloads/AI-Waifu-Vtuber-master (1)/AI-Waifu-Vtuber-master/run.py"
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Error transcribing audio
Recording...
Stopped recording.
Error transcribing audio
Recording...
Stopped recording.
Error transcribing audio
Recording...
Stopped recording.
Error transcribing audio
Recording...
Stopped recording.
Error transcribing audio

**Comment by ardha27** [comment]
Read my readme on FAQ section

**Comment by KiyoshiTheBoss** [comment]
after i do that and save i got this error 
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)> & "C:/Program Files/Python311/python.exe" "c:/Users/60107/Downloads/AI-Waifu-Vtuber-master (1)/AI-Waifu-Vtuber-master/run.py"
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Traceback (most recent call last):
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 243, in <module>
    record_audio()
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 77, in transcribe_audio
    transcript = openai.Audio.transcribe("whisper-1", audio_file)
                 ^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'Audio'

**Comment by ardha27** [comment]
It said that you don't have this file characterConfig/Pina/identity.txt. Did you already clone my repository?

**Comment by KiyoshiTheBoss** [comment]
oh need to clone it back?

**Comment by KiyoshiTheBoss** [comment]
> It said that you don't have this file characterConfig/Pina/identity.txt. Did you already clone my repository?

yes i downlaod the repositary using zip file

**Comment by ardha27** [comment]
Do you have this file on your zip? characterConfig/Pina/identity.txt

**Comment by KiyoshiTheBoss** [comment]
> Do you have this file on your zip? characterConfig/Pina/identity.txt

yes  there is

**Comment by KiyoshiTheBoss** [comment]
should i install back and and do extract here?

**Comment by ardha27** [comment]
Ss me, from which directory you start the program

**Comment by KiyoshiTheBoss** [comment]
like this ?

PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master> & "C:/Program Files/Python311/python.exe" "c:/Users/60107/Downloads/AI-Waifu-Vtuber-master (1)/AI-Waifu-Vtuber-master/run.py"
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Yes! 1, 2, 3...
Traceback (most recent call last):
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 243, in <module>       
    record_audio()
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio    
    transcribe_audio("input.wav")
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 84, in transcribe_audio
    openai_answer()
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 108, in openai_answer
    prompt = getPrompt()
             ^^^^^^^^^^^
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\promptMaker.py", line 16, in getPrompt
    prompt.append(getIdentity("characterConfig/Pina/identity.txt"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\promptMaker.py", line 9, in getIdentity
    with open(identityPath, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'characterConfig/Pina/identity.txt'

**Comment by KiyoshiTheBoss** [comment]
it slowly getting better XD

PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master> python .\run.py
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Test, 1, 2, 3, hello.
JP Answer: こんにちは。
Traceback (most recent call last):
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 243, in <module>
    record_audio()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 84, in transcribe_audio
    openai_answer()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 120, in openai_answer
    translate_text(message)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 198, in translate_text
    voicevox_tts(tts)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\TTS.py", line 35, in voicevox_tts
    params_encoded = urllib.parse.urlencode({'text': katakana_text, 'speaker': 46})

**Comment by ardha27** [comment]
did you already run VoiceVox?

**Comment by KiyoshiTheBoss** [comment]
ahhh i see okay i try do that

**Comment by KiyoshiTheBoss** [comment]
i run voicevox in collab 
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master> python .\run.py
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Hello Yoda, how are you?
JP Answer: 名前のユナ。私は大丈夫です。
Traceback (most recent call last):
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 243, in <module>
    record_audio()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 84, in transcribe_audio
    openai_answer()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 120, in openai_answer
    translate_text(message)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 198, in translate_text
    voicevox_tts(tts)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\TTS.py", line 35, in voicevox_tts
    params_encoded = urllib.parse.urlencode({'text': katakana_text, 'speaker': 46})
                                                     ^^^^^^^^^^^^^

**Comment by ardha27** [comment]
change the voicevox url link on TTS.py using the link you got from colab

**Comment by KiyoshiTheBoss** [comment]
like this as example https://lemon-groups-serve-35-199-176-248.loca.lt/

**Comment by KiyoshiTheBoss** [comment]
i dont understand how to use collab vox so i tried use locally

and still got this 
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master> python .\run.py
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Yes, how are you?
JP Answer: 私はうまく機能しています。
Traceback (most recent call last):
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 243, in <module>
    record_audio()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 84, in transcribe_audio
    openai_answer()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 120, in openai_answer
    translate_text(message)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\run.py", line 198, in translate_text
    voicevox_tts(tts)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master (1)\AI-Waifu-Vtuber-master\utils\TTS.py", line 35, in voicevox_tts
    params_encoded = urllib.parse.urlencode({'text': katakana_text, 'speaker': 46})
                                                     ^^^^^^^^^^^^^
NameError: name 'katakana_text' is not defined
