### ISSUE TITLE
NameError: name 'tts_en' is not defined

### ISSUE THREAD

**Issue by grigorzero** [ardha27/AI-Waifu-Vtuber#22]
Hello, i try to follow your step by step, but i got error like this. 

Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: 
JP Answer: アルダは何と言ったのですか？
Traceback (most recent call last):
  File "C:\Users\GRIGORZERO\Documents\AI VTUBER\AI-Waifu-Vtuber-master\run.py", line 246, in <module>
    record_audio()
  File "C:\Users\GRIGORZERO\Documents\AI VTUBER\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "C:\Users\GRIGORZERO\Documents\AI VTUBER\AI-Waifu-Vtuber-master\run.py", line 87, in transcribe_audio
    openai_answer()
  File "C:\Users\GRIGORZERO\Documents\AI VTUBER\AI-Waifu-Vtuber-master\run.py", line 123, in openai_answer
    translate_text(message)
  File "C:\Users\GRIGORZERO\Documents\AI VTUBER\AI-Waifu-Vtuber-master\run.py", line 204, in translate_text
    silero_tts(tts_en, "en", "v3_en", "en_21")
**NameError: name 'tts_en' is not defined**

I want to use silero and already try to install "pip install silero"
Should i added import silero at your 'run.py'?

Oh yeah i already change it to Silero too

    # Choose between the available TTS engines
    # Japanese TTS
    #voicevox_tts(tts)

    # Silero TTS, Silero TTS can generate English, Russian, French, Hindi, Spanish, German, etc. Uncomment the line below. Make sure the input is in that language
    silero_tts(tts_en, "en", "v3_en", "en_21") 

Pls halp

**Comment by ardha27** [comment]
uncomment line 191 
![image](https://user-images.githubusercontent.com/48845217/230602843-f998d4be-748d-41c4-b7bc-ef1cf39a8dbc.png)

**Comment by grigorzero** [comment]
It did it!! the AI respond to my voice, but after a while it doesnt respond again. Is it normal?
It stuck at 

Press and Hold Right Shift to record audio
Recording...
Stopped recording.

Does it because the AI takes a long of time to answer question with voice? 
Also thank you so much for helping me btw

**Comment by ardha27** [comment]
I think somthing happening on openai API, because mine also get slow respond. Idk either
