### ISSUE TITLE
Weird issue after latest update

### ISSUE THREAD

**Issue by Atsukohirota** [ardha27/AI-Waifu-Vtuber#28]
Typed python .\run.py chose 1=mic. it responded then errored 
![image](https://user-images.githubusercontent.com/130300501/230781141-61eb069f-ced7-46cd-888f-119f25fb5ca2.png)

**Comment by Atsukohirota** [comment]
![image](https://user-images.githubusercontent.com/130300501/230781083-a4c2a1c9-6f62-48d4-8c31-c661827b6324.png)

At the end it says runtime error

**Comment by Atsukohirota** [comment]
![image](https://user-images.githubusercontent.com/130300501/230781166-23242a98-6c5b-497e-86b1-6eea2f159ba9.png)

**Comment by ardha27** [comment]
Read FAQ about mecab

**Comment by Atsukohirota** [comment]
It has nothing to do with mecab. After it responds with an answer it does that error

**Comment by ardha27** [comment]
Yes it is, on your first Screenshot it said error about mecab

**Comment by Atsukohirota** [comment]
It has nothing to do with mecab. I tried it after making changes to fix the mecab error and it didnt change.

**Comment by Atsukohirota** [comment]
After reinstalling python and rerunning the pip install -r requirements.txt. I still have the same issue

Here is the entirety of everything from the cmd.

PS D:\Games\AI-Waifu-Vtuber-master> python .\run.py
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: You
JP Answer: あなたは私に質問をしていますか、それとも声明を出していますか？
EN Answer: Are you asking me a question or making a statement?
Traceback (most recent call last):
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 248, in <module>   
    record_audio()
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 87, in transcribe_audio
    openai_answer()
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 120, in openai_answer
    translate_text(message)
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 203, in translate_text
    voicevox_tts(tts)
  File "D:\Games\AI-Waifu-Vtuber-master\utils\TTS.py", line 32, in voicevox_tts
    katakana_text = katakana_converter(tts)
  File "D:\Games\AI-Waifu-Vtuber-master\utils\katakana.py", line 15, in katakana_converter    
    wakati = MeCab.Tagger('-Owakati')
  File "D:\python\lib\site-packages\MeCab.py", line 355, in __init__
    _MeCab.Tagger_swiginit(self, _MeCab.new_Tagger(*args))
RuntimeError

**Comment by ardha27** [comment]
It's mecab problem

**Comment by Atsukohirota** [comment]
just did the mecab fix and it does not fix the problem. Traceback (most recent call last):
  File "D:\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\python\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "D:\python\lib\http\client.py", line 975, in send
    self.connect()
  File "D:\python\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020DD4A57310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50021): Max retries exceeded with url: /audio_query?text=%E3%82%A2%E3%83%84%E3%82%B3%E3%83%92%E3%83%AD%E3%82%BF%E3%81%AF%E4%BD%95%E3%81%A8%E8%A8%80%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E3%81%99%E3%81%8B%EF%BC%9F&speaker=46 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD4A57310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 248, in <module>
    record_audio()
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 87, in transcribe_audio
    openai_answer()
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 120, in openai_answer
    translate_text(message)
  File "D:\Games\AI-Waifu-Vtuber-master\run.py", line 203, in translate_text
    voicevox_tts(tts)
  File "D:\Games\AI-Waifu-Vtuber-master\utils\TTS.py", line 34, in voicevox_tts
    request = requests.post(f'{voicevox_url}/audio_query?{params_encoded}')
  File "D:\python\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=50021): Max retries exceeded with url: /audio_query?text=%E3%82%A2%E3%83%84%E3%82%B3%E3%83%92%E3%83%AD%E3%82%BF%E3%81%AF%E4%BD%95%E3%81%A8%E8%A8%80%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E3%81%99%E3%81%8B%EF%BC%9F&speaker=46 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD4A57310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by Atsukohirota** [comment]
then maybe its a mecab error.

**Comment by Atsukohirota** [comment]
error is fixed so closing this
