### ISSUE TITLE
Voicevox on colab

### ISSUE THREAD

**Issue by Adolfiux** [ardha27/AI-Waifu-Vtuber#33]
Help please : /

Traceback (most recent call last):
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\run.py", line 244, in <module>
    record_audio()
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\run.py", line 87, in transcribe_audio
    openai_answer()
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\run.py", line 120, in openai_answer
    translate_text(message)
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\run.py", line 199, in translate_text
    voicevox_tts(tts)
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\utils\TTS.py", line 38, in voicevox_tts
    request = requests.post(f'{voicevox_url}/synthesis?{params_encoded}', json=request.json())
  File "I:\python\AI-Waifu-Vtuber-master\AI-Waifu-Vtuber-master\env\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Adolfiux** [comment]
The problem is that voicevox is not giving me a response from Google Colab. I've tried changing the port and checking that it's running, but nothing seems to work. It worked fine the first day I tried it, but not anymore. I also noticed that the code in Colab isn't utilizing GPU resources, so I'm not sure if that has anything to do with it.

**Comment by Adolfiux** [comment]
But if i use this command in Google Colab:

!nvidia-smi 

I get this:;

`Thu Apr 13 06:14:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

The colab is running using the GPU unit, but the problem is the response from the url.

**Comment by ViccenzoBertoche** [comment]
I have the same problem, i can access to voicevox, because googlecolab isn't running it. It seems to be running but in resources gpu use is 0%, google colab isnt using the gpu

**Comment by ducpham611** [comment]
Hi, it's a bit late but i am trying to run the voicevox on colab too, but i keep getting this error on colab when using the url given from colab. If possible, can you show me how to run it properly on colab, thank you.
Error: connection refused: localtunnel.me:46773 (check your firewall settings)
    at Socket.<anonymous> (/tools/node/lib/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
