### ISSUE TITLE
Error with Mecab

### ISSUE THREAD

**Issue by Kleat** [ardha27/AI-Waifu-Vtuber#44]
is there any idea what is causing the following error when i attempt to run run.py? i've installed mecab with the command pip install mecab as well.

ImportError: DLL load failed while importing _MeCab: The specified module could not be found.

**Comment by ardha27** [comment]
it's known issues and some people also facing it, but idk what is the real problem. For now you can follow the FAQ on my github about mecab error

**Comment by Tomiiiix** [comment]
I solved this problem by removing python and everything , and then re-installing it again.

**Comment by tkyin17** [comment]
You will need to install the MeCab 64-bit binary if you are using Python 64-bit as per the instructions on https://pypi.org/project/mecab/

**Comment by dontaco2000** [comment]
I believe this is happening because the script is using MeCab instead of the more updated mecab-python3
https://pypi.org/project/mecab-python3/

**Comment by dontaco2000** [comment]
(base) C:\AI-Vtuber>python run.py
Traceback (most recent call last):
  File "C:\AI-Vtuber\run.py", line 16, in <module>
    from utils.TTS import *
  File "C:\AI-Vtuber\utils\TTS.py", line 5, in <module>
    from utils.katakana import *
  File "C:\AI-Vtuber\utils\katakana.py", line 1, in <module>
    import MeCab
  File "C:\Users\donta\AppData\Roaming\Python\Python310\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: The specified module could not be found.

**Comment by noakosar515** [comment]
I have same errors. How can I do?

**Comment by noakosar515** [comment]
I have solved this problem. I installed mecab.

**Comment by Kthunda** [comment]
Had the same problem, and found a solution :

Manually copy libmecab.dll from:

`C:\Users\<YourUsername>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\lib\site-packages\MeCab\`

to this folder:

`C:\Users\<YourUsername>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\MeCab\`
