### ISSUE TITLE
Silero tts not working

### ISSUE THREAD

**Issue by ducpham611** [ardha27/AI-Waifu-Vtuber#90]
I just uncomment the silero tts in run.py and it give me this error. If possible, can you tell me how to fix this, thank you.
Traceback (most recent call last):
  File "G:\Test AI Vtuber\AI-Waifu-Vtuber\run.py", line 248, in <module>       
    record_audio()
  File "G:\Test AI Vtuber\AI-Waifu-Vtuber\run.py", line 68, in record_audio    
    transcribe_audio("input.wav")
  File "G:\Test AI Vtuber\AI-Waifu-Vtuber\run.py", line 87, in transcribe_audio
    openai_answer()
  File "G:\Test AI Vtuber\AI-Waifu-Vtuber\run.py", line 120, in openai_answer
    translate_text(message)
  File "G:\Test AI Vtuber\AI-Waifu-Vtuber\run.py", line 206, in translate_text
    silero_tts(tts_en, "en", "v3_en", "en_21")
  File "G:\Test AI Vtuber\AI-Waifu-Vtuber\utils\TTS.py", line 23, in silero_tts
    audio_paths = model.save_wav(text=tts,
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<torch_package_0>.multi_acc_v3_package.py", line 366, in save_wav
  File "<torch_package_0>.multi_acc_v3_package.py", line 316, in apply_tts
  File "<torch_package_0>.multi_acc_v3_package.py", line 63, in prepare_tts_model_input
  File "<torch_package_0>.multi_acc_v3_package.py", line 91, in process_simple_text
ValueError

**Comment by RomiconEZ** [comment]
I have the same problem when using the local English-language model TTS en_v3. Have you found a solution?

**Comment by ducpham611** [comment]
@RomiconEZ I haven't found any solution for that. It seems like he hadn't updated this project for a long time. Sorry I couldn't help you anything.
