### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joireum** [ardha27/AI-Waifu-Vtuber#91]
An error message appears as shown below.

Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Traceback (most recent call last):
  File "run.py", line 245, in <module>
    record_audio()
  File "run.py", line 68, in record_audio
    transcribe_audio("input.wav")
  File "run.py", line 77, in transcribe_audio
    transcript = openai.Audio.transcribe("whisper-1", audio_file)
  File "C:\Users\joire\AppData\Local\Programs\Python\Python38\lib\site-packages\openai\api_resources\audio.py", line 72, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
  File "C:\Users\joire\AppData\Local\Programs\Python\Python38\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\joire\AppData\Local\Programs\Python\Python38\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\joire\AppData\Local\Programs\Python\Python38\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

![image](https://github.com/ardha27/AI-Waifu-Vtuber/assets/66953695/282e19b1-d15c-44c6-b1b6-84a3729b3971)

but shows that I have free usage remaining, so why does this error occur?

**Comment by ardha27** [comment]
there are limit for request per minute

**Comment by joireum** [comment]
Solved. Thank you.
