### ISSUE TITLE
I followed read.me, but it seems like the package versions are different and there is a conflict.

### ISSUE THREAD

**Issue by Junghigh** [ardha27/AI-Waifu-Vtuber#96]
C:\Users\jinu\AppData\Local\Programs\Python\Python312\python.exe C:\Users\jinu\Py\AI-Waifu-Vtuber-master\run.py 
Traceback (most recent call last):
  File "C:\Users\jinu\Py\AI-Waifu-Vtuber-master\run.py", line 1, in <module>
    import openai
  File "C:\Users\jinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\jinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .image import Image as Image
  File "C:\Users\jinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\types\image.py", line 5, in <module>
    from .._models import BaseModel
  File "C:\Users\jinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\_models.py", line 25, in <module>
    from ._types import (
  File "C:\Users\jinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\openai\_types.py", line 23, in <module>
    from httpx import URL, Proxy, Timeout, Response, BaseTransport, AsyncBaseTransport
ImportError: cannot import name 'BaseTransport' from 'httpx' (C:\Users\jinu\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\__init__.py). Did you mean: 'ASGITransport'?

I already installed -r requirements.txt 
There was no problem installing it except for Mecab.
How can I do this?

**Comment by Yunicar** [comment]
same issue here any update?
